"""
Django settings for gestion_donnee project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url  
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Détection de l'environnement
DEBUG = os.environ.get("DEBUG", "True") == "True"
SECRET_KEY = 'django-insecure-*m92$s_h&u99xn-(*d6e+b)521gez7*6y31$y)rxitg6$^e(o9'

ALLOWED_HOSTS = ["localhost", "127.0.0.1", ".onrender.com"]
CSRF_TRUSTED_ORIGINS = ["https://tech-inforoute-projet1.onrender.com/"]



# --- Configuration base de données ---
if os.environ.get("RENDER"):  # En production sur Render
    DATABASES = {
        "default": dj_database_url.parse(
            os.environ.get("DATABASE_URL"),
            conn_max_age=600,
            ssl_require=True
        )
    }
else:  # En local, tu gardes MySQL
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": "gestion_donnee_db",
            "USER": "root",
            "PASSWORD": "root",
            "HOST": "127.0.0.1",
            "PORT": "3306",
        }
    }

# --- Static files ---
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')



# Application definition

INSTALLED_APPS = [
    'jazzmin',       
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    "drf_yasg",
    "graphene_django",
    "corsheaders",
    "rest_framework",
    "rest_framework.authtoken", 
   
    
    'api_graphql',
    'users',
    "recup_donnee", 
    "frontend",
    "api_rest",
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

CORS_ALLOW_ALL_ORIGINS = True # autorise toutes les origines (tous les domaines) à accéder à ton API Django.
                              # Autrement dit, n'importe quel site web peut envoyer des requêtes à l'API, 
                              # et Django ne les bloquera pas.

CORS_ALLOW_CREDENTIALS = True
ROOT_URLCONF = 'gestion_donnee.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],        
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
WSGI_APPLICATION = 'gestion_donnee.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



# Développement
STATICFILES_DIRS = [
    BASE_DIR / "frontend" / "static",  
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}
GRAPHENE = {
    "SCHEMA": "api_graphql.schema.schema"
}


JAZZMIN_SETTINGS = {
    "site_title": "OGSL Admin",
    "site_header": "OGSL Dashboard",
    "site_brand": "OGSL",
    "welcome_sign": "Bienvenue dans l’espace administrateur",
    "show_sidebar": True,
    "show_recent": False, 
    "custom_css": "frontend/custom.css", 
    "icons": {
        "recup_donnee.Dataset": "fas fa-database",
        "recup_donnee.Contact": "fas fa-user",
        "recup_donnee.Publication": "fas fa-book",
        "recup_donnee.DateInfo": "fas fa-calendar-alt",
    },
   
    "topmenu_links": [
        {"name": "Accueil", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Statistiques", "url": "/admin/recup_donnee/dataset/stats/", "new_window": False},
    ],

}
