# Generated by Django 5.2.7 on 2025-10-31 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_dataverse', models.CharField(max_length=500, verbose_name='Nom')),
                ('identifier_of_dataverse', models.CharField(default='UNKNOWN', max_length=255, verbose_name='Identifiant Dataverse')),
                ('url', models.URLField(verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('keywords', models.TextField(blank=True, null=True, verbose_name='Mots-clés')),
                ('subjects', models.TextField(blank=True, null=True, verbose_name='Sujets')),
                ('authors', models.TextField(blank=True, null=True, verbose_name='Auteurs')),
            ],
            options={
                'verbose_name': 'Jeu de données',
                'verbose_name_plural': 'Jeux de données',
            },
        ),
        migrations.CreateModel(
            name='HarvestConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(verbose_name='Source de moissonnage')),
                ('frequency', models.CharField(help_text='Ex: quotidienne, hebdomadaire', max_length=100, verbose_name='Fréquence')),
                ('filters', models.TextField(blank=True, null=True, verbose_name='Filtres appliqués')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Moissonnage',
                'verbose_name_plural': 'Moissonnages',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('affiliation', models.CharField(blank=True, max_length=500, null=True, verbose_name='Affiliation')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='recup_donnee.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='DateInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(verbose_name='Date de modification')),
                ('published_at', models.DateTimeField(verbose_name='Date de publication')),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='date_info', to='recup_donnee.dataset')),
            ],
            options={
                'verbose_name': 'Date',
                'verbose_name_plural': 'Dates',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation', models.TextField(verbose_name='Citation')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='recup_donnee.dataset')),
            ],
        ),
    ]
